### ISSUE TITLE
Changing image file does not trigger reload

### ISSUE THREAD

**Issue by riknoll** [omefire/cordova-plugin-livereload#15]
While testing with the stock Hello Cordova app on Android, I changed the contents of logo.png. The console noted the file change, but no reload was triggered. Changing another file (index.html) after changing the image did cause a reload and the new image to be reflected in the application.

**Comment by omefire** [comment]
@riknoll, what do you mean by changing the .png file ?
Did you remove it, then add it back to the folder it was in ?

**Comment by riknoll** [comment]
I overwrote it (pasted a file to replace it from clipboard)

**Comment by omefire** [comment]
Closed as this was resolved by this PR: https://github.com/omefire/cordova-plugin-livereload/pull/34
