### ISSUE TITLE
Expose a Node like API

### ISSUE THREAD

**Issue by panarasi** [omefire/cordova-plugin-livereload#38]
It would be great to have a Node like API exposed for this plugin. This will enable other tools that depend on this to integrate better.

Here is an example I had for 2 main parts - a `Patcher` which is responsible for modifying the Cordova server, and the browserSync server itself. 

https://github.com/nparashuram/cordova-plugin-browsersync/tree/master/lib/utils

**Comment by omefire** [comment]
An interface to expose an API for this has been handled in this PR:
https://github.com/omefire/cordova-plugin-livereload/pull/44

Thanks for the suggestion.
