### ISSUE TITLE
white screen on ios with -- --livereload

### ISSUE THREAD

**Issue by istrion** [omefire/cordova-plugin-livereload#48]
Hi , i got a white screen on my emulator, if i run with :

 cordova run ios -- --livereload

someone got a idea ?

thx :-)

**Comment by omefire** [comment]
haaa, I know what's going on here. the ios emulator tries to connect to 'localhost' instead of 'external', I will work on a fix soon.

**Comment by omefire** [comment]
Hey @istrion, this issue has been fixed with the following PR: https://github.com/omefire/cordova-plugin-livereload/pull/53

Could you please try it out and let me know if it now works for you ?
