### ISSUE TITLE
livereload runs without explicitly using --livereload 

### ISSUE THREAD

**Issue by 1N50MN14** [omefire/cordova-plugin-livereload#49]
Hi there,

First, thanks for a great plugin, a life saver!

I'm facing couple of issues:
1) When launching the app using `cordova run --device`, i.e. without explicitly using `--livereload`, the plugin still runs. I'm on OS X, latest cordova and node version 4.2.

2)  `CTRL+C` doesn't seem to kill the livereload process, I have to manually kill it.

**Comment by omefire** [comment]
Hey, thanks for filing this issue. I was able to repro it.

**Comment by omefire** [comment]
For some reason, nopt parses the `--device` option as `--devicesync`. (`devicesync` is/was synonymous to `--livereload`).

**Comment by omefire** [comment]
I just issued a fix for this issue, try it again and let me know if things work fine for you.

**Comment by omefire** [comment]
The "CTRL+C" issue not working on ios is due to the way "ios-sim" works, there's no way to get around it on a version of cordova-ios less than 3.9.2, I think.

**Comment by 1N50MN14** [comment]
@omefire Yup that worked, thanks for the fix!

**Comment by omefire** [comment]
Cool. @1N50MN14 let me know if you find any other issues.
